version: "3.7"
services:
#   pgadmin:
#     image: dpage/pgadmin4
#     init: true
#     container_name: pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: test@test.pl
#       PGADMIN_DEFAULT_PASSWORD: test
#     ports:
#       - "80:80"
#     depends_on:
#       - postgres
  postgres:
    image: postgres
    init: true
    container_name: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./kolokwium:/home
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
